sudo: required 
services:
  - docker

before_install:
  - docker build -t abdulaleem-git/docker-react -f Dockerfile.dev .

script:
  - docker run abdulaleem-git/docker-react npm run test -- --coverage


